-- Jalankan sekali di Supabase SQL Editor untuk kategori, pencarian, dan produk populer.

create table if not exists public.catalog_categories (
  id bigint generated by default as identity primary key,
  bot_id bigint not null references public.telegram_bot_settings(bot_id) on delete cascade,
  name text not null check (char_length(name) between 2 and 50),
  created_at timestamptz not null default now(),
  unique (bot_id, name)
);

alter table public.catalog_products
  add column if not exists category_id bigint references public.catalog_categories(id) on delete set null,
  add column if not exists view_count integer not null default 0 check (view_count >= 0);

create index if not exists catalog_categories_bot_idx
  on public.catalog_categories (bot_id, name);

create index if not exists catalog_products_popular_idx
  on public.catalog_products (bot_id, is_active, view_count desc, created_at desc);

alter table public.catalog_categories enable row level security;
revoke all on table public.catalog_categories from anon, authenticated;

select pg_notify('pgrst', 'reload schema');
