-- Jalankan sekali di Supabase SQL Editor untuk mengaktifkan fitur katalog.

create table if not exists public.catalog_products (
  id bigint generated by default as identity primary key,
  bot_id bigint not null references public.telegram_bot_settings(bot_id) on delete cascade,
  name text not null check (char_length(name) between 2 and 100),
  price bigint not null check (price >= 0),
  description text not null default '' check (char_length(description) <= 2000),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists catalog_products_bot_active_idx
  on public.catalog_products (bot_id, is_active, created_at desc);

alter table public.catalog_products
  add column if not exists image_url text;

alter table public.catalog_products enable row level security;
revoke all on table public.catalog_products from anon, authenticated;
select pg_notify('pgrst', 'reload schema');
