-- Katalink Telegram: persistent encrypted bot configuration
-- Jalankan sekali melalui Supabase Dashboard > SQL Editor.

create table if not exists public.telegram_bot_settings (
  id text primary key,
  bot_id bigint not null unique,
  bot_first_name text not null,
  bot_username text,
  token_encrypted text not null,
  webhook_secret text not null,
  webhook_url text not null,
  welcome_text text not null,
  whatsapp_number text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- No client-side role needs access. The Vercel server function uses the
-- server-only Supabase service_role key, which bypasses RLS.
alter table public.telegram_bot_settings enable row level security;
revoke all on table public.telegram_bot_settings from anon, authenticated;

-- Product catalog. Each catalog belongs to the one Telegram bot configured above.
create table if not exists public.catalog_products (
  id bigint generated by default as identity primary key,
  bot_id bigint not null references public.telegram_bot_settings(bot_id) on delete cascade,
  name text not null check (char_length(name) between 2 and 100),
  price bigint not null check (price >= 0),
  description text not null default '' check (char_length(description) <= 2000),
  image_url text,
  sort_order integer not null default 999999,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists catalog_products_bot_active_idx
  on public.catalog_products (bot_id, is_active, created_at desc);

alter table public.catalog_products enable row level security;
revoke all on table public.catalog_products from anon, authenticated;
